
REWARD = 0
PUNISHMENT = -10000
ALPHA = 0.7
ALPHA_MIN = 0.1
ALPHA_DECREASE_START = 21
ALPHA_DECREASE_END = 34
GAMMA = 0.95
EPSILON = 0.0314
EPSILON_DECREASE_START = 0
EPSILON_DECREASE_END = 5


ACTION_FLAP = "FLAP"
ACTION_NOTHING = "NOTHING"
ACTIONS = [ACTION_NOTHING, ACTION_FLAP]

NUMBER_OF_ITERATION = 1

FILE_QTABLE = './qtable.dat'
